CREATE DATABASE IF NOT EXISTS MRJEFFDB;

CREATE TABLE `MRJEFFDB`.`CUPON_DESCUENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODIGO` VARCHAR(100) NOT NULL,
  `VALOR` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CODIGO_UNIQUE` (`CODIGO` ASC) VISIBLE);
